/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as GrandmasterUsernameImport } from './routes/grandmaster/$username'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GrandmasterUsernameRoute = GrandmasterUsernameImport.update({
  path: '/grandmaster/$username',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/grandmaster/$username': {
      id: '/grandmaster/$username'
      path: '/grandmaster/$username'
      fullPath: '/grandmaster/$username'
      preLoaderRoute: typeof GrandmasterUsernameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  GrandmasterUsernameRoute,
})

/* prettier-ignore-end */
